WebXe/Controllers/CarModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebXe.Models;
using WebXe.ViewModels;
using Microsoft.AspNet.Identity;

namespace WebXe.Controllers
{
    public class CarModelsController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CarModelsController()
        {
            _dbContext = new ApplicationDbContext();
        }

        public ActionResult Index(int id)
        {
            var model = _dbContext.CarModels.Find(id);
            return View(model);
        }

        public FileContentResult GetImage(int imageid)
        {
            CarImages images = _dbContext.CarImages.Where(n => n.Id == imageid).Single();
            try
            {
                return new FileContentResult(images.Image, "image/jpeg");
            }
            catch (Exception ex)
            {
            }
            return null;
        }
    }
}

WebXe/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebXe.Models;

namespace WebXe.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public HomeController()
        {
            _dbContext = new ApplicationDbContext();
        }

        public FileContentResult GetImage(int id, int indexa)
        {
            List<CarImages> list = _dbContext.CarImages.Where(n => n.CarModelId.Equals(id)).ToList();
            try
            {
                return new FileContentResult(list[indexa].Image, "image/jpeg");
            }
            catch(Exception ex)
            {
            }
            return null;
        }

        public ActionResult Index(int id = 1)
        {
            var content = _dbContext.CarModels.ToList();

            int countPage = Convert.ToInt32(Math.Ceiling((double)content.Count / 5));
            if (countPage == 0)
                countPage = 1;

            if (id <= 0)
                id = 1;
            else if (id >= countPage)
                id = countPage;

            ViewBag.NowPage = id;
            ViewBag.CountPage = countPage;

            List<CarModels> viewContent = new List<CarModels>();
            for (int i = id*5-5; i<id*5; i++)
            {
                try
                {
                    viewContent.Add(content[i]);
                }
                catch(Exception ex)
                {
                }
            }

            return View(viewContent);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";
            return View();
        }
    }
}

WebXe/Views/Home/About.cshtml
@{
    ViewBag.Title = "Về Chúng Tôi";
}
<h2>Trang Web rao bán xe đã qua sử dụng.</h2>
<h3>Mang lại lợi ích về chi phí mua bán trao đổi xe, phương tiện đi lại.</h3>

<p></p>

WebXe/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>Contact Us:</h3>

<h5>
    Phone: 08 408 8888
</h5>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">AdminTeam@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">MarketingTeam@example.com</a>
</address>

WebXe/Views/Home/Index.cshtml
@model List<WebXe.Models.CarModels>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main-content">
    @foreach (var models in Model)
    {
    models.GetListImagesId();
    <div class="item-content">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h3>@models.Name</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 item-image">
                    @if (models.ListImages.Count > 0)
                    {
                    <img src="@Url.Action("GetImage", new { id = models.Id, indexa = 0 })"/>
                    }
                    else 
                    {
                    <img src="~/Source/noimage.png" />
                    }
                </div>

                <div class="col-md-6 body">
                    <div class="row item-description">
                        <h4>@models.Content</h4>
                    </div>
                    <div class="row item-thumbnail">
                        @if (models.ListImages.Count > 5)
                        {
                            for (int index = 1; index < 5; index++)
                            {
                            <img src="@Url.Action("GetImage", new { id = models.Id, indexa = index })" />
                            }
                        }
                        else
                        {
                            for (int index = 1; index < models.ListImages.Count; index++)
                            {
                            <img src="@Url.Action("GetImage", new { id = models.Id, indexa = index })" />
                            }
                        }
                    </div>
                </div>

                <div class="col-md-2 item-info">
                    
                    <h4>@(models.FormatMoney(models.Price))VNĐ</h4>
                    <h4>@(models.FormatMoney(models.PricePublic))VNĐ</h4>
                    @Html.ActionLink("Xem Chi Tiết", "Index", "CarModels", new {id = models.Id}, new {@class = "item-button-view btn btn-primary"})
                </div>
            </div>
        </div>
    </div>
    }

    <div class="pagination">
        @Html.ActionLink("Sau", "Index", new { id = (ViewBag.NowPage <= 1) ? ViewBag.NowPage : ViewBag.NowPage-1 })
        @foreach (int pages in Model.FirstOrDefault().GeneratePaginationList(ViewBag.NowPage, ViewBag.CountPage))
        {
            if (ViewBag.NowPage == pages)
            {
                @Html.ActionLink(pages.ToString(), "Index", new { id = pages }, new { @class = "active" })
            }
            else
            {
                @Html.ActionLink(pages.ToString(), "Index", new { id = pages })
            }
        }
        @Html.ActionLink("Tiếp", "Index", new { id = (ViewBag.NowPage >= ViewBag.CountPage) ? ViewBag.NowPage : ViewBag.NowPage+1 })
    </div>
</div>